* Encoding: UTF-8.
* CCHS Variance amongst groups statistical test
* By Haifeng Yu
* 2018-07-30

* This tests the median of number of visits to medical doctor amongst different groups.
* Using the K-W test and Median test to validate statistical significance amongst groups

DATASET ACTIVATE DataSet1.
NPAR TESTS
  /K-W=CHPGMDC BY DHH_SEX(1 2)
  /MEDIAN=CHPGMDC BY DHH_SEX(1 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY DHHGAGE(1 16)
  /MEDIAN=CHPGMDC BY DHHGAGE(1 16)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY INCGPER(1 6)
  /MEDIAN=CHPGMDC BY INCGPER(1 6)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY DHHGHSZ(1 5)
  /MEDIAN=CHPGMDC BY DHHGHSZ(1 5)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY SDCGCGT(1 2)
  /MEDIAN=CHPGMDC BY SDCGCGT(1 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY SDCGCB13(1 2)
  /MEDIAN=CHPGMDC BY SDCGCB13(1 2)
  /MISSING ANALYSIS.

NPAR TESTS 
  /K-W=CHPGMDC BY DHH_OWN(1 2) 
  /MEDIAN=CHPGMDC BY DHH_OWN(1 2) 
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY PACDPAI(1 3)
  /MEDIAN=CHPGMDC BY PACDPAI(1 3)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY HWTGISW(1 4)
  /MEDIAN=CHPGMDC BY HWTGISW(1 4)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY CCC_035(1 2)
  /MEDIAN=CHPGMDC BY CCC_035(1 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY CCC_036(1 2)
  /MEDIAN=CHPGMDC BY CCC_036(1 2)
  /MISSING ANALYSIS.

NPAR TESTS
  /K-W=CHPGMDC BY AWC(0 1)
  /MEDIAN=CHPGMDC BY AWC(0 1)
  /MISSING ANALYSIS.

